# Generated by Django 2.1.1 on 2018-09-29 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(default='', max_length=100, verbose_name='Ders Adi')),
                ('kategori', models.ManyToManyField(help_text='Ders seçiniz', to='hesap.Category', verbose_name='Ders')),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme', models.IntegerField(default=0, verbose_name='Odeme')),
                ('alinan_dersler', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alinan_dersler', to='hesap.Dersler')),
            ],
            options={
                'verbose_name_plural': 'Odeme',
            },
        ),
        migrations.CreateModel(
            name='Ogretmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik_adi', models.CharField(max_length=240)),
            ],
            options={
                'verbose_name_plural': 'Öğretmenler',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ad ve Soyad Giriniz')),
                ('draft', models.BooleanField(default=False, verbose_name='Taslak olusturulsun mu?')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Resim')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('Tarih', models.DateTimeField(default=datetime.datetime(2018, 10, 29, 14, 4, 55, 786655))),
                ('ders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hesap.Dersler', verbose_name='Dersler')),
                ('icerik', models.ManyToManyField(help_text='Öğretmen Seçiniz', to='hesap.Ogretmen', verbose_name='Öğretmen')),
            ],
            options={
                'verbose_name_plural': 'Gönderiler',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Ucret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucret', models.IntegerField(default=0, verbose_name='Ucret')),
                ('ders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ders', to='hesap.Dersler', verbose_name='Ders')),
            ],
            options={
                'verbose_name_plural': 'Ucret',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='ucret',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hesap.Ucret'),
        ),
    ]
