# Generated by Django 2.1.1 on 2018-09-29 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesap', '0003_auto_20180929_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ucret',
        ),
        migrations.AlterField(
            model_name='post',
            name='Tarih',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 14, 11, 20, 705656)),
        ),
    ]
